/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as ClasseActifsRouteImport } from './routes/classe-actifs'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as SignauxRouteImport } from './routes/signaux'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasseActifsRoute = ClasseActifsRouteImport.update({
  id: '/classe-actifs',
  path: '/classe-actifs',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const SignauxRoute = SignauxRouteImport.update({
  id: '/signaux',
  path: '/signaux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/classe-actifs': typeof ClasseActifsRoute
  '/cycles': typeof CyclesRoute
  '/funding': typeof FundingRoute
  '/sentiment': typeof SentimentRoute
  '/signaux': typeof SignauxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/classe-actifs': typeof ClasseActifsRoute
  '/cycles': typeof CyclesRoute
  '/funding': typeof FundingRoute
  '/sentiment': typeof SentimentRoute
  '/signaux': typeof SignauxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/classe-actifs': typeof ClasseActifsRoute
  '/cycles': typeof CyclesRoute
  '/funding': typeof FundingRoute
  '/sentiment': typeof SentimentRoute
  '/signaux': typeof SignauxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/classe-actifs'
    | '/cycles'
    | '/funding'
    | '/sentiment'
    | '/signaux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/classe-actifs'
    | '/cycles'
    | '/funding'
    | '/sentiment'
    | '/signaux'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/classe-actifs'
    | '/cycles'
    | '/funding'
    | '/sentiment'
    | '/signaux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  ClasseActifsRoute: typeof ClasseActifsRoute
  CyclesRoute: typeof CyclesRoute
  FundingRoute: typeof FundingRoute
  SentimentRoute: typeof SentimentRoute
  SignauxRoute: typeof SignauxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classe-actifs': {
      id: '/classe-actifs'
      path: '/classe-actifs'
      fullPath: '/classe-actifs'
      preLoaderRoute: typeof ClasseActifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaux': {
      id: '/signaux'
      path: '/signaux'
      fullPath: '/signaux'
      preLoaderRoute: typeof SignauxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  ClasseActifsRoute: ClasseActifsRoute,
  CyclesRoute: CyclesRoute,
  FundingRoute: FundingRoute,
  SentimentRoute: SentimentRoute,
  SignauxRoute: SignauxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
